---
- name: Palo Alto Playbook
  hosts: paloalto
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Test
      debug:
      - msg: "Test message"
