---
- name: Palo Alto Playbook
  hosts: paloalto
  gather_facts: true
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: 10.10.2.85
      username: 'admin_rw'
      password: 'pass_admin_rw'
    search_rule_name: 'BGP'

  tasks:
    - name: Test
      debug:
        msg: "Test message: PaloAlto"

    - name: Get facts
      paloaltonetworks.panos.panos_facts:
        provider: '{{ provider }}'
        gather_subset: ['config']
        
